// Code generated by command: go run asm.go -out bidobo.s -stubs stub.go. DO NOT EDIT.

package bidobo

func blockSortUpwardBy8ElementsOf4Bytes(T []uint32, i int, gap int) int

func blockSortDownwardBy8ElementsOf4Bytes(T []uint32, i int, gap int) int

func blockSortUpwardBy4ElementsOf4Bytes(T []uint32, i int, gap int) int

func blockSortDownwardBy4ElementsOf4Bytes(T []uint32, i int, gap int) int

func blockSortUpwardBy4ElementsOf8Bytes(T []uint64, i int, gap int) int

func blockSortDownwardBy4ElementsOf8Bytes(T []uint64, i int, gap int) int
